Title: "Open Coding Society Security"
TeamName: "CCCS"
Logo: "capstone/cccs-security-logo.jpg"
Overview: "The Open Coding Society Security project focuses on enhancing cybersecurity awareness and skills among students. It aims to provide hands-on experience with security tools, practices, and real-world scenarios to prepare students for challenges in the field of cybersecurity."
Team: ["Lucas Masterson", "Jacob Chou", "Zhengji Li"]